import { useEffect, useState, type FormEvent } from 'react';
import { CalendarClock, RefreshCw } from 'lucide-react';

type Watch = { id:string; court_name:string; court_number:string; user_item_number:number; status:string; running_item_number?:number; last_checked_at?:string };
export function CourtQueueView() {
  const [watches,setWatches]=useState<Watch[]>([]); const [error,setError]=useState(''); const [form,setForm]=useState({courtName:'',courtNumber:'',itemNumber:''});
  const load=async()=>{try{const r=await fetch('/api/queue');const p=await r.json();if(!r.ok)throw new Error(p.error);setWatches(p.watches);}catch(e){setError(e instanceof Error?e.message:'Unable to load watches.');}}; useEffect(()=>{void load();},[]);
  const create=async(e:FormEvent)=>{e.preventDefault();setError('');try{const r=await fetch('/api/queue',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});const p=await r.json();if(!r.ok)throw new Error(p.error);setForm({courtName:'',courtNumber:'',itemNumber:''});void load();}catch(e){setError(e instanceof Error?e.message:'Unable to create watch.');}};
  return <div className="pt-14 px-6 pb-6 min-h-screen"><div className="mb-5"><h1 className="font-display text-2xl font-semibold" style={{color:'var(--text-primary)'}}>Court Queue Alert</h1><p className="text-sm mt-1" style={{color:'var(--text-tertiary)'}}>Persistent watches are polled by Vercel Cron, not an in-memory server loop.</p></div>{error&&<p className="mb-3 text-sm" style={{color:'var(--risk-critical)'}}>{error}</p>}<form onSubmit={create} className="rounded-xl border p-4 grid grid-cols-1 md:grid-cols-4 gap-3" style={{borderColor:'var(--border)',background:'var(--bg-surface)'}}>{[['courtName','Court name'],['courtNumber','Court number'],['itemNumber','Your item number']].map(([key,label])=><input key={key} required value={(form as any)[key]} onChange={e=>setForm({...form,[key]:e.target.value})} placeholder={label} className="rounded-md px-3 py-2 bg-transparent border" style={{borderColor:'var(--border)',color:'var(--text-primary)'}}/>)}<button style={{background:'var(--accent)',color:'var(--bg-base)'}} className="rounded-md py-2">Arm watch</button></form><button onClick={load} className="flex gap-2 items-center text-xs mt-5" style={{color:'var(--accent)'}}><RefreshCw size={14}/>Refresh watch state</button><div className="space-y-3 mt-3">{watches.map(w=><div key={w.id} className="rounded-xl border p-4 flex gap-4 items-center" style={{borderColor:'var(--border)',background:'var(--bg-surface)'}}><CalendarClock style={{color:'var(--accent)'}}/><div><p style={{color:'var(--text-primary)'}}>{w.court_name} · Court {w.court_number}</p><p className="text-xs" style={{color:'var(--text-tertiary)'}}>Item {w.user_item_number} · {w.status}{w.running_item_number!=null?` · board on ${w.running_item_number}`:''}</p></div></div>)}{!watches.length&&!error&&<p className="text-sm" style={{color:'var(--text-tertiary)'}}>No queue watches yet.</p>}</div></div>;
}
