/* eslint-disable @typescript-eslint/no-explicit-any */
import { useState } from 'react';
import { MODULES } from '../data';
import type { EvidenceNode, ModuleDef } from '../types';
import { UploadZone, type UploadedFile } from '../components/UploadZone';
import { EvidenceBoard } from '../components/EvidenceBoard';

interface Props {
  module: ModuleDef;
  sharedFiles: UploadedFile[];
  onSharedFiles: (files: UploadedFile[]) => void;
  moduleResults: Record<string, any>;
  onResult: (moduleId: string, result: any) => void;
}
async function base64(file: File) { const data = new Uint8Array(await file.arrayBuffer()); let binary = ''; data.forEach(b => binary += String.fromCharCode(b)); return btoa(binary); }
function asNodes(moduleId: ModuleDef['id'], result: any): EvidenceNode[] {
  const groups = result.results || [result]; const flags = groups.flatMap((g: any) => g.flags || g.result?.flags || []);
  return flags.map((f: any, i: number) => ({ id: `${moduleId}-${i}`, label: f.risk_type || f.party_role || f.pleaded_ground || f.topic_a || f.concession || 'Review signal', detail: f.explanation || f.suggested_rewrite || f.prayer_gap || f.summary || JSON.stringify(f), ref: f.paragraph_reference || f.ground_paragraph_reference || f.legal_basis || 'AI analysis', severity: (f.severity === 'critical' || f.risk_type === 'admission' || f.party_type === 'necessary') ? 'critical' : 'warning', docId: 'analysis', page: 1, x: 15 + (i * 21) % 70, y: 20 + (i * 17) % 60, suggestion: f.suggested_rewrite || f.recommendation || undefined }));
}
export function ModuleView({ module, sharedFiles, onSharedFiles, moduleResults, onResult }: Props) {
  const [phase, setPhase] = useState<'upload'|'results'>(module.hasUpload ? 'upload' : 'results'); const [result, setResult] = useState<any>(moduleResults[module.id] ?? null); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const [citation, setCitation] = useState(''); const [direction, setDirection] = useState<'outgoing'|'incoming'>('outgoing'); const [contradictionTarget, setContradictionTarget] = useState<'opponent'|'own'>('opponent');
  async function run(files: UploadedFile[]) { setBusy(true); setError(''); try { if (module.id !== 'citation') onSharedFiles(files); const documents = await Promise.all(files.map(async f => ({ name:f.name, mimeType:f.file.type, fileBase64:await base64(f.file) }))); const missingPartyContext = module.id === 'prayer-pleading' && moduleResults['missing-party'] ? JSON.stringify(moduleResults['missing-party'].flags ?? []) : undefined; const response = await fetch('/api/analyze', { method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify({module:module.id, documents, direction, contradictionTarget, missingPartyContext}) }); const payload = await response.json(); if (!response.ok || !payload.success) throw new Error(payload.error || 'The analysis could not be completed.'); setResult(payload.result); onResult(module.id, payload.result); setPhase('results'); } catch (e) { setError(e instanceof Error ? e.message : 'The analysis could not be completed.'); } finally { setBusy(false); } }
  async function runCitation() { setBusy(true); setError(''); try { const response = await fetch('/api/analyze',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({module:'citation',citation})}); const payload=await response.json(); if(!response.ok||!payload.success) throw new Error(payload.error||'Citation check failed.'); setResult(payload.result); } catch(e){setError(e instanceof Error?e.message:'Citation check failed.');} finally {setBusy(false);} }
  const nodes = result ? asNodes(module.id, result) : [];
  const citationResults = module.id === 'citation' && result ? result.results ?? [] : [];
  return <div className="flex flex-col h-full pt-14 px-6 pb-6" style={{minHeight:'calc(100vh - 3.5rem)'}}><div className="mb-5 stagger-in" style={{'--i':0} as React.CSSProperties}><h1 className="font-display text-2xl font-semibold" style={{color:'var(--text-primary)'}}>{module.name}</h1><p className="text-sm mt-1 max-w-2xl" style={{color:'var(--text-tertiary)'}}>{module.description}</p></div>
    {error && <div className="mb-4 p-3 rounded-lg text-sm" style={{color:'var(--risk-critical)',background:'var(--risk-critical-bg)'}}>{error}</div>}
    {module.id === 'trapdoor' && <fieldset className="mb-4 flex gap-2 text-sm" aria-label="Correspondence direction"><button onClick={()=>setDirection('outgoing')} className="px-3 py-1.5 rounded border" style={{borderColor:'var(--border)',background:direction==='outgoing'?'var(--bg-elevated)':'transparent'}}>Outgoing</button><button onClick={()=>setDirection('incoming')} className="px-3 py-1.5 rounded border" style={{borderColor:'var(--border)',background:direction==='incoming'?'var(--bg-elevated)':'transparent'}}>Incoming</button></fieldset>}
    {module.id === 'contradiction' && <fieldset className="mb-4 flex gap-2 text-sm" aria-label="Filings to check"><button onClick={()=>setContradictionTarget('opponent')} className="px-3 py-1.5 rounded border" style={{borderColor:'var(--border)',background:contradictionTarget==='opponent'?'var(--bg-elevated)':'transparent'}}>Check opponent's filings</button><button onClick={()=>setContradictionTarget('own')} className="px-3 py-1.5 rounded border" style={{borderColor:'var(--border)',background:contradictionTarget==='own'?'var(--bg-elevated)':'transparent'}}>Check our own filings</button></fieldset>}
    {module.id === 'citation' && <div className="max-w-2xl rounded-xl border p-5" style={{borderColor:'var(--border)',background:'var(--bg-surface)'}}><label className="text-sm" style={{color:'var(--text-secondary)'}}>Citation to verify</label><div className="flex gap-2 mt-2"><input value={citation} onChange={e=>setCitation(e.target.value)} placeholder="e.g. (2024) 1 SCC 100" className="flex-1 rounded-lg px-3 py-2 bg-transparent border" style={{borderColor:'var(--border)',color:'var(--text-primary)'}}/><button disabled={busy} onClick={runCitation} className="px-4 rounded-lg" style={{background:'var(--accent)',color:'var(--bg-base)'}}>{busy?'Checking…':'Check'}</button></div></div>}
    {module.hasUpload && phase==='upload' && <div className="flex-1 flex flex-col items-center justify-center py-8 gap-4">{sharedFiles.length>0 && <button disabled={busy} onClick={()=>run(sharedFiles)} className="px-4 py-2 rounded-lg text-sm" style={{background:'var(--accent)',color:'var(--bg-base)', opacity: busy ? 0.7 : 1}}>{busy ? 'Analyzing…' : `Analyze ${sharedFiles.length} shared case document${sharedFiles.length===1?'':'s'}`}</button>}<UploadZone moduleLabel={module.shortName} onAnalyze={run} busy={busy}/></div>}
    {result && <><button onClick={()=>{setPhase('upload');setResult(null);}} className="text-xs w-fit px-3 py-1.5 rounded-md border mb-3" style={{borderColor:'var(--border)',color:'var(--text-secondary)'}}>← New analysis</button>{module.id === 'citation' ? <div className="max-w-3xl space-y-3"><div className="text-sm" style={{color:'var(--text-secondary)'}}>{result.note || `${result.analyzed_count} grounded result${result.analyzed_count===1?'':'s'}.`} <span style={{color:'var(--text-tertiary)'}}>Cache: {result.cache_status}; Google searches today: {result.daily_search_queries_used}.</span></div>{citationResults.map((item:any)=><article key={item.source_url} className="rounded-xl border p-4" style={{borderColor:'var(--border)',background:'var(--bg-surface)'}}><div className="flex justify-between gap-3"><a href={item.source_url} target="_blank" rel="noreferrer" className="font-medium underline" style={{color:'var(--accent)'}}>{item.citing_case}</a><span className="text-xs capitalize" style={{color:'var(--text-secondary)'}}>{item.treatment} · {item.confidence}</span></div><p className="text-sm mt-2" style={{color:'var(--text-primary)'}}>{item.supporting_passage}</p><p className="text-xs mt-2" style={{color:'var(--text-tertiary)'}}>{item.source_type === 'full_page_fetched' ? 'Full page fetched' : 'Google search snippet only'} · {item.jurisdictional_note}</p></article>)}{citationResults.length===0 && <div className="rounded-xl border p-4 text-sm" style={{borderColor:'var(--border)',color:'var(--text-secondary)'}}>No citing cases were found in the configured authoritative sources.</div>}</div> : <EvidenceBoard nodes={nodes} links={[]} summary={nodes.length ? `${nodes.length} real analysis signal${nodes.length===1?'':'s'} returned.${module.id==='contradiction' ? ` Showing ${contradictionTarget==='own'?'our own':'opposing party’s'} filing framing.` : ''}` : 'Analysis completed with no review signals.'} moduleId={module.id}/>}</>}
  </div>;
}
export { MODULES };
