import { useState, useRef } from 'react';
import { UploadCloud, FileText, X, Clipboard, Loader2 } from 'lucide-react';

export interface UploadedFile { id: string; name: string; size: string; type: string; file: File; }
interface Props { moduleLabel: string; onAnalyze: (files: UploadedFile[]) => Promise<void>; maxFiles?: number; busy?: boolean; }

export function UploadZone({ moduleLabel, onAnalyze, maxFiles = 5, busy = false }: Props) {
  const [files, setFiles] = useState<UploadedFile[]>([]); const [dragging, setDragging] = useState(false); const inputRef = useRef<HTMLInputElement>(null);
  const add = (items: File[]) => setFiles(p => [...p, ...items.slice(0, maxFiles - p.length).map(file => ({ id: crypto.randomUUID(), name: file.name, size: `${Math.ceil(file.size / 1024)} KB`, type: file.type || 'Document', file }))]);
  return <div className="w-full max-w-3xl mx-auto"><div className="text-center mb-6"><h2 className="font-display text-2xl font-semibold mb-1" style={{color:'var(--text-primary)'}}>Upload documents for {moduleLabel}</h2><p className="text-sm" style={{color:'var(--text-tertiary)'}}>PDF, image, TXT and DOCX files are processed by the secure analysis API. No sample data is used.</p></div>
    <div onDrop={e=>{e.preventDefault();setDragging(false);add(Array.from(e.dataTransfer.files));}} onDragOver={e=>{e.preventDefault();setDragging(true);}} onDragLeave={()=>setDragging(false)} tabIndex={0} className="relative rounded-2xl border-2 border-dashed p-10 text-center transition-all duration-200 outline-none" style={{borderColor:dragging?'var(--accent)':'var(--border-strong)',background:dragging?'var(--bg-elevated)':'var(--bg-surface)'}}><div className="flex flex-col items-center gap-3"><div className="w-14 h-14 rounded-xl flex items-center justify-center" style={{background:'var(--bg-elevated)',border:'1px solid var(--border)'}}><UploadCloud size={26} style={{color:'var(--accent)'}} /></div><p className="text-base font-medium" style={{color:'var(--text-primary)'}}>Drop documents here, or <button onClick={()=>inputRef.current?.click()} className="underline underline-offset-2" style={{color:'var(--accent-bright)'}}>browse</button></p><p className="text-xs flex items-center gap-1" style={{color:'var(--text-tertiary)'}}><Clipboard size={12}/> Maximum {maxFiles} documents</p></div><input ref={inputRef} type="file" multiple className="hidden" onChange={e=>{add(Array.from(e.target.files||[])); e.target.value='';}}/></div>
    {files.length>0 && <div className="mt-4 space-y-2">{files.map(f=><div key={f.id} className="flex items-center gap-3 px-4 py-2.5 rounded-lg border" style={{borderColor:'var(--border)',background:'var(--bg-elevated)'}}><FileText size={16} style={{color:'var(--accent)'}}/><div className="flex-1 min-w-0"><div className="text-sm font-medium truncate" style={{color:'var(--text-primary)'}}>{f.name}</div><div className="font-mono text-xs" style={{color:'var(--text-tertiary)'}}>{f.type} · {f.size}</div></div><button onClick={()=>setFiles(p=>p.filter(x=>x.id!==f.id))} aria-label={`Remove ${f.name}`}><X size={14}/></button></div>)}<button disabled={busy} onClick={()=>onAnalyze(files)} className="w-full mt-3 py-3 rounded-lg font-medium text-sm" style={{background:'var(--accent)',color:'var(--bg-base)',opacity:busy?.7:1}}>{busy?<span className="flex justify-center gap-2"><Loader2 className="animate-spin" size={16}/>Analysing…</span>:<>Run {moduleLabel} →</>}</button></div>}</div>;
}
